import turtle


class Drawing:
    def __init__(self):
        self.alex = turtle.Turtle()
        self.window = turtle.Screen()
        self.window.bgcolor("green")
        self.window.tracer(1)
        self.window.tracer(True)
        self.alex.pencolor("black")
        self.alex.pensize = 0.2

        self.scale = 25

    def draw_test_frame(self):
        self.alex.pencolor("white")
        self.alex.pendown()
        self.alex.forward(4 * self.scale)
        self.alex.left(90)
        self.alex.forward(7 * self.scale)
        self.alex.left(90)
        self.alex.forward(4 * self.scale)
        self.alex.left(90)
        self.alex.forward(7 * self.scale)
        self.alex.left(90)
        self.alex.pencolor("black")

    def draw_space(self, units):
        self.alex.penup()
        self.alex.forward(units * self.scale)

    def draw_0(self):
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(2 * self.scale)
        self.alex.right(90)
        self.alex.left(-90)
        self.alex.pendown()
        self.alex.circle(2 * self.scale, 180)
        self.alex.forward(3 * self.scale)
        self.alex.circle(2 * self.scale, 180)
        self.alex.forward(3 * self.scale)
        self.alex.penup()
        self.alex.forward(2 * self.scale)
        self.alex.left(90)
        self.alex.forward(4 * self.scale)

    def draw_1(self):
        self.alex.penup()
        self.alex.forward(3.5 * self.scale)
        self.alex.left(90)
        self.alex.pendown()
        self.alex.forward(7 * self.scale)
        self.alex.left(135)
        self.alex.forward(4.5 * self.scale)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(4.5 * self.scale)
        self.alex.right(135)
        self.alex.forward(7 * self.scale)
        self.alex.left(90)
        self.alex.forward(0.5 * self.scale)

    def draw_2(self):
        self.alex.penup()
        self.alex.forward(4 * self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.forward(4 * self.scale)
        self.alex.right(135)
        self.alex.forward(5 * self.scale)
        self.alex.circle(2 * self.scale, 225)
        self.alex.penup()
        self.alex.forward(4.95 * self.scale)
        self.alex.left(90)
        self.alex.forward(3.9 * self.scale)

    def draw_3(self):
        self.alex.penup()
        self.alex.forward(0.25 * self.scale)
        self.alex.left(90)
        self.alex.forward(1.75 * self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.circle(1.75 * self.scale, 270)
        self.alex.right(180)
        self.alex.circle(1.75 * self.scale, 270)
        self.alex.penup()
        self.alex.forward(5.25 * self.scale)
        self.alex.left(90)
        self.alex.forward(3.75 * self.scale)

    def draw_4(self):
        self.alex.penup()
        self.alex.forward(3 * self.scale)
        self.alex.left(90)
        self.alex.forward(4 * self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.forward(4 * self.scale)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(3 * self.scale)
        self.alex.right(90)
        self.alex.forward(self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.forward(4 * self.scale)
        self.alex.right(120)
        self.alex.forward(4.6 * self.scale)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(4.6 * self.scale)
        self.alex.left(120)
        self.alex.right(90)
        self.alex.forward(3 * self.scale)
        self.alex.left(90)
        self.alex.forward(4 * self.scale)

    def draw_5(self):
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(2 * self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.circle(2 * self.scale, 270)
        self.alex.forward(1.5 * self.scale)
        self.alex.right(90)
        self.alex.forward(3 * self.scale)
        self.alex.right(90)
        self.alex.forward(3.5 * self.scale)
        self.alex.penup()
        self.alex.right(90)
        self.alex.forward(7 * self.scale)
        self.alex.left(90)

    def draw_6(self):
        self.alex.penup()
        self.alex.forward(2 * self.scale)
        self.alex.pendown()
        self.alex.circle(2 * self.scale, 360)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(2 * self.scale)
        self.alex.right(90)
        self.alex.forward(2 * self.scale)
        self.alex.pendown()
        self.alex.forward(3 * self.scale)
        self.alex.right(90)
        self.alex.penup()
        self.alex.forward(4 * self.scale)
        self.alex.right(270)
        self.alex.pendown()
        self.alex.circle(2 * self.scale, 180)
        self.alex.penup()
        self.alex.forward(5 * self.scale)
        self.alex.left(90)
        self.alex.forward(4 * self.scale)

    def draw_7(self):
        self.alex.penup()
        self.alex.forward(self.scale)
        self.alex.left(68)
        self.alex.pendown()
        self.alex.forward(7.5 * self.scale)
        self.alex.left(112)
        self.alex.forward(3.7 * self.scale)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(3.7 * self.scale)
        self.alex.right(112)
        self.alex.forward(4 * self.scale)
        self.alex.pendown()
        self.alex.right(68)
        self.alex.forward(1.5 * self.scale)
        self.alex.right(180)
        self.alex.forward(3 * self.scale)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(1.5 * self.scale)
        self.alex.left(68)
        self.alex.forward(3.5 * self.scale)
        self.alex.right(68)
        self.alex.right(180)
        self.alex.forward(3 * self.scale)

    def draw_8(self):
        self.alex.penup()
        self.alex.forward(2 * self.scale)
        self.alex.pendown()
        self.alex.circle(1.75 * self.scale)
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(3.5 * self.scale)
        self.alex.pendown()
        self.alex.right(90)
        self.alex.circle(1.75 * self.scale)
        self.alex.penup()
        self.alex.forward(2 * self.scale)
        self.alex.right(90)
        self.alex.forward(3.5 * self.scale)
        self.alex.left(90)

    def draw_9(self):
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(3.5 * self.scale)
        self.alex.right(90)
        self.alex.forward(2 * self.scale)
        self.alex.pendown()
        self.alex.circle(1.75 * self.scale)
        self.alex.circle(1.75 * self.scale, 90)
        self.alex.right(180)
        self.alex.forward(3.5 * self.scale)
        self.alex.right(180)
        self.alex.circle(1.75 * self.scale, -180)
        self.alex.penup()
        self.alex.forward(1.75 * self.scale)
        self.alex.left(90)
        self.alex.forward(3.75 * self.scale)

    def draw_root_symbol(self, x):
        self.alex.penup()
        self.alex.right(90)
        self.alex.forward(0.5 * self.scale)
        self.alex.left(90)
        self.alex.left(90)
        self.alex.forward(3 * self.scale)
        self.alex.pendown()
        self.alex.right(90)
        self.scale /= 2 # tutaj
        self.draw_3() #  zmiana
        self.scale *= 2 # potrzebna
        self.alex.right(180)
        self.alex.forward(2 * self.scale)
        self.alex.right(90)
        self.alex.right(180)
        self.alex.forward(self.scale)
        self.alex.right(180)
        self.alex.pendown()
        self.alex.right(90)
        self.alex.forward(self.scale)
        self.alex.right(60)
        self.alex.forward(2.2 * self.scale)
        self.alex.right(120)
        self.alex.right(180)
        self.alex.left(75)
        self.alex.forward(8 * self.scale)
        self.alex.right(75)
        self.alex.forward(x * 4 * self.scale)
        self.alex.forward(0.5 * self.scale)
        self.alex.right(90)
        self.alex.forward(self.scale)
        self.alex.left(90)
        self.alex.penup()
        self.alex.right(180)
        self.alex.forward(x * 4 * self.scale)
        self.alex.forward(0.65 * self.scale)
        self.alex.left(90)
        self.alex.forward(6.3 * self.scale)
        self.alex.left(90)

    def draw_x(self):
        self.alex.pendown()
        self.alex.left(45)
        self.alex.forward(pow(2, (1 / 2)) * 4 * self.scale)
        self.alex.left(225)
        self.alex.penup()
        self.alex.forward(4 * self.scale)
        self.alex.left(225)
        self.alex.pendown()
        self.alex.forward(pow(2, (1 / 2)) * 4 * self.scale)
        self.alex.left(225)
        self.alex.penup()
        self.alex.forward(4 * self.scale)
        self.alex.right(90)
        self.alex.forward(4 * self.scale)
        self.alex.left(90)

    def draw_fraction(self, a, b, x, y): # do zmiany
        n = (a - b) // 2
        self.alex.penup()
        self.alex.right(90)
        self.alex.forward(0.5 * a)
        self.alex.left(90)
        self.alex.forward(4 * n)
        self.alex(b)
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(0.5 * a)
        self.alex.right(90)
        self.alex.forward(4 * n)
        self.alex.left(90)
        self.alex.forward(3.5 * a)
        self.alex.left(90)
        self.alex.pendown()
        self.alex.forward(4 * a)
        self.alex.right(180)
        self.alex.forward(4 * n)
        self.alex.penup()
        self.alex.left(90)
        self.alex.forward(0.5 * a)
        self.alex.right(90)
        self.alex.forward(0.5 * a)
        self.alex.pendown()
        self.draw_0(b)
        self.alex.penup()
        self.alex.forward(0.75 * a)
        self.alex.right(90)
        self.alex.forward(4 * a)
        self.alex.left(90)

